name: vIcmAr Binance Bot

on:
  schedule:
    - cron: '0 */3 * * *'  # Se ejecuta cada 3 horas
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install requests groq python-dotenv

      - name: Ejecutar Bot
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          SQUARE_API_KEY: ${{ secrets.SQUARE_API_KEY }}
        run: python main.py