name: Radar Señales Futuros

on:
  schedule:
    - cron: '15 10-23,0-2 * * *'  # Activo de 07:00 a 23:00 hora Argentina (UTC-3)
  workflow_dispatch:      # Botón manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install requests groq python-dotenv selenium webdriver-manager google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Ejecutar Bot de Futuros
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          MODO_PRUEBA: 'False'
          GROQ_MODEL_NAME: "llama-3.3-70b-versatile"
          TIPO_BOT: "FUTUROS"  # Activa la nueva lógica
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          ID_TELEGRAM: ${{ secrets.ID_TELEGRAM }}
        run: python main.py